name: spendex
description: Spendex - A comprehensive personal finance management mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  crypto: ^3.0.7
  dartz: ^0.10.1
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  enough_mail: ^2.1.6
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_analytics: ^10.8.5
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_phosphor_icons: ^0.0.1+6
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_sms_inbox: ^1.0.2
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  intl: ^0.20.2
  jiffy: ^6.2.1
  json_annotation: ^4.8.1
  local_auth: ^2.1.8
  lottie: ^3.0.0
  mobile_scanner: ^4.0.1
  modal_bottom_sheet: ^3.0.0
  open_filex: ^4.4.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  pinput: ^4.0.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  razorpay_flutter: ^1.3.6
  reactive_forms: ^17.0.1
  riverpod_annotation: ^2.3.3
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  speech_to_text: ^6.6.0
  url_launcher: ^6.2.4
  uuid: ^4.3.1
  vibration: ^1.8.4
  webview_flutter: ^4.5.0

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  golden_toolkit: ^0.15.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env
