name: spendex
description: Spendex - A comprehensive personal finance management mobile application
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.0
  crypto: ^3.0.7
  dartz: ^0.10.1
  device_info_plus: ^10.0.0
  dio: ^5.4.0
  enough_mail: ^2.1.6
  equatable: ^2.0.5
  file_picker: ^8.0.0
  firebase_analytics: ^12.1.2
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  firebase_messaging: 16.1.1
  firebase_performance: ^0.11.1+4
  firebase_remote_config: ^6.1.4
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^7.0.1
  flutter_jailbreak_detection: ^1.10.0
  flutter_local_notifications: ^18.0.0
  flutter_localizations:
    sdk: flutter
  flutter_phosphor_icons: ^0.0.1+6
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_sms_inbox: ^1.0.2
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_windowmanager: ^0.2.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.0.0
  google_fonts: ^6.1.0
  google_mlkit_text_recognition: ^0.14.0
  google_sign_in: ^6.2.1
  hive: any
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_cropper: ^8.0.0
  image_picker: ^1.0.7
  in_app_review: ^2.0.8
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  intl: ^0.20.2
  jiffy: ^6.2.1
  json_annotation: ^4.8.1
  local_auth: ^2.1.8
  logger: ^2.0.2
  lottie: ^3.0.0
  mobile_scanner: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  open_filex: ^4.4.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  pinput: ^5.0.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  razorpay_flutter: ^1.3.6
  riverpod_annotation: ^2.3.3
  safe_device: ^1.1.6
  share_plus: ^10.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.3
  speech_to_text: ^7.3.0
  url_launcher: ^6.2.4
  uuid: ^4.3.1
  vibration: ^2.0.0
  webview_flutter: ^4.5.0
dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.4.1
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.4.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.9
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env
  generate: true

dependency_overrides:
  speech_to_text_windows:
    path: packages/speech_to_text_windows_stub

